apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: sasachde/vote:v4
        name: vote
