apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 5
  template:
    spec:
      containers:
      - image: sasachde/vote:v3
        name: vote
        resources:
          requests:
            memory: "8Mi"
            cpu: "50m"
          limits:
            memory: "16Mi"
            cpu: "80m"
        envFrom:
          - configMapRef:
              name: vote-options
              optional: true
