apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
#- service.yaml
replicas:
- name: vote
  count: 4
images:
- name: sasachde/vote
  newTag: main-e670959e-1673076111 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
